<?php

/**
 * @file
 * Contains hearsay_automation_process.module.
 */

/**
 * Implements hook_cron().
 */
function hearsay_automation_process_cron()
{
    try {
        $objHSUtility = \Drupal::service('hearsay_automation_process_service.utility');
        $objHSUtility->logMessage .= "API cron started.<br/>";
        $queue = \Drupal::queue('hs_queue_processing');
        $noOfItemsInQueueBeforeProcessing = $queue->numberOfItems();
        $queue->deleteQueue();
        $responseData = [];
        // Fetch data to process queue.
        $responseData = $objHSUtility->getAllSitesFromAPI();
        // Get customized preview data.
        $previewData = $objHSUtility->createPreviewSlug();
        array_push($responseData, $previewData);
        // Adding preview slug data.
        if ($responseData) {
            $arrFinalItemsToProcess = $objHSUtility->getDataItemsWithProcessingAction($responseData);
            if ($arrFinalItemsToProcess) {
                foreach ($arrFinalItemsToProcess as $item) {
                    // Process each element in queue.
                    $queue->createItem($item);
                }
            }
        }
        $noOfItemsInQueueAfterProcessing = $queue->numberOfItems();
        $objHSUtility->logMessage .= 'Perviously queue were having ' . print_r($noOfItemsInQueueBeforeProcessing, true);
        $objHSUtility->logMessage .= '.Currently Queue has ' . print_r($noOfItemsInQueueAfterProcessing, true) . ' items.<br/>';
        $objHSUtility->logMessage .= "API cron completed successfully.<br/>";
        \Drupal::logger('hearsay_automation_process')->notice($objHSUtility->logMessage);
    } catch (\Exception $e) {
        \Drupal::logger('hearsay_automation_process')->error('API Import failed.');
    }
}
