<?php

/**
 * @file
 * This module adds a Layout operation link for Layout Builder-enabled content.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\layout_builder\Plugin\SectionStorage\OverridesSectionStorage;

/**
 * Implements hook_entity_operation().
 */
function layout_builder_operation_link_entity_operation(EntityInterface $entity) {
  $account = \Drupal::currentUser();
  $entity_type_id = $entity->getEntityTypeId();

  $route_name = "layout_builder.overrides.$entity_type_id.view";
  $route_parameters = [
    $entity_type_id => $entity->id(),
  ];
  $route_options = [];

  // If current user has access to route, then add the operation link. The
  // access check will only return TRUE if the bundle is Layout Builder-
  // enabled, overrides are allowed, and user has necessary permissions.
  $access_manager = \Drupal::service('access_manager');
  if (!$access_manager->checkNamedRoute($route_name, $route_parameters, $account)) {
    return;
  }

  // Add entity's language as a route option if layouts are translatable
  // (e.g. the Layout Builder Asymmetric Translation contrib module
  // is installed).
  if ($entity instanceof FieldableEntityInterface
    && $entity->hasField(OverridesSectionStorage::FIELD_NAME)
    && $entity->get(OverridesSectionStorage::FIELD_NAME)->getFieldDefinition()->isTranslatable()
  ) {
    $route_options['language'] = $entity->language();
  }

  return [
    'layout' => [
      'title' => t('Layout'),
      'weight' => 50,
      'url' => Url::fromRoute($route_name, $route_parameters, $route_options),
    ],
  ];
}

/**
 * Implements template_preprocess_links().
 */
function layout_builder_operation_link_preprocess_links(&$variables) {
  if ($variables['theme_hook_original'] == 'links__dropbutton__operations'
    && isset($variables['links']['layout']['link'])
    ) {
    // The 'destination' query parameter is hardcoded by
    // \Drupal\views\Plugin\views\field\EntityOperations::render().
    // Until https://www.drupal.org/project/drupal/issues/2950883 is committed,
    // we need to remove the 'destination' parameter to prevent it from
    // overriding the form state redirect set by
    // \Drupal\layout_builder\Form\OverridesEntityForm::redirectOnSubmit().
    unset($variables['links']['layout']['link']['#options']['query']['destination']);
  }
}

/**
 * Implements hook_help().
 */
function layout_builder_operation_link_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the layout_builder_operation_link module.
    case 'help.page.layout_builder_operation_link':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Layout Builder Operation Link module adds a <em>Layout</em> operation link for Layout Builder-enabled content.') . '</p>';

      return $output;
  }
}
