<?php

/**
 * @file
 * Provides a curriculum reservation entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\surf_curriculum\Entity\CurriculumReservation;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function surf_curriculum_theme() {
  return [
    'curriculum_reservation' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for curriculum reservation templates.
 *
 * Default template: curriculum-reservation.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the curriculum reservation information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_curriculum_reservation(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function surf_curriculum_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_reassign':
      // Anonymize curriculum reservations.
      $storage = \Drupal::entityTypeManager()->getStorage('curriculum_reservation');
      $curriculum_reservation_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($curriculum_reservation_ids) as $curriculum_reservation) {
        $curriculum_reservation->setOwnerId(0);
        $curriculum_reservation->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function surf_curriculum_user_predelete(UserInterface $account) {
  // Delete curriculum reservations.
  $storage = \Drupal::entityTypeManager()->getStorage('curriculum_reservation');
  $curriculum_reservation_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $curriculum_reservations = $storage->loadMultiple($curriculum_reservation_ids);
  $storage->delete($curriculum_reservations);
}
