<?php

/**
 * @file
 * Install, update and uninstall functions for the SURF Migrate module.
 */

/**
 * Remove schema value for removed modules.
 */
function surf_migrate_update_10001() {
  $removed_modules = [
    'ckeditor',
    'conditional_fields',
    'insert_view',
    'mercury_editor_layouts',
    'mercury_editor_skip_form',
    'rdf'
  ];
  foreach ($removed_modules as $key) {
    \Drupal::keyValue("system.schema")->delete($key);
  }
}

