_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
module:
  action: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  backup_migrate: 0
  ban: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  content_access: 0
  contextual: 0
  ctools: 0
  date_range_formatter: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  entityqueue: 0
  field: 0
  field_group: 0
  field_tools: 0
  field_ui: 0
  file: 0
  filefield_paths: 0
  filter: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  imce: 0
  inline_entity_form: 0
  insert_view: 0
  link: 0
  maxlength: 0
  media: 0
  media_library: 0
  menu_block: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_tools: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pathauto: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  scheduler: 0
  search: 0
  shortcut: 0
  simple_block: 0
  structure_sync: 0
  surf_migrate: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  update: 0
  user: 0
  views_infinite_scroll: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  bartik: 0
  seven: 0
  radix: 0
  surf: 0
profile: standard
