_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
module:
  action: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  apitools: 0
  auto_entitylabel: 0
  automated_cron: 0
  backup_migrate: 0
  ban: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  config: 0
  contact: 0
  contextual: 0
  crop: 0
  ctools: 0
  date_range_formatter: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  download_request: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entity: 0
  entity_reference_display: 0
  entity_reference_revisions: 0
  entityqueue: 0
  field: 0
  field_group: 0
  field_tools: 0
  field_ui: 0
  file: 0
  filefield_paths: 0
  filter: 0
  gin_toolbar: 0
  google_analytics: 0
  honeypot: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  key: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  layout_paragraphs: 0
  link: 0
  mailsystem: 0
  maxlength: 0
  media: 0
  media_library: 0
  menu_item_extras: 0
  menu_ui: 0
  mercury_editor: 0
  mercury_editor_templates: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_d8: 0
  migrate_plus: 0
  migrate_tools: 0
  mysql: 0
  name: 0
  node: 0
  notification_message: 0
  optional_end_date: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  path: 0
  path_alias: 0
  pathauto: 0
  phpass: 0
  rabbit_hole: 0
  redirect: 0
  redirect_404: 0
  responsive_image: 0
  scheduler: 0
  sdc: 0
  search_api: 0
  search_api_block: 0
  search_api_pantheon: 0
  search_api_solr: 0
  serialization: 0
  shortcut: 0
  similarterms: 0
  smart_date: 0
  state_machine: 0
  structure_sync: 0
  style_options: 0
  surf_admin: 0
  surf_core: 0
  surf_curriculum: 0
  surf_dashboard: 0
  surf_migrate: 0
  surf_registration: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  twig_field_value: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_filters_summary: 0
  views_infinite_scroll: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_content_creator: 0
  webform_ui: 0
  webform_user_registration: 0
  menu_link_content: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  claro: 0
  gin: 0
  stable9: 0
  surf_main: 0
profile: standard
