_core:
  default_config_hash: '-hIna-Wer82f4uUFdPEmBNA6-RerV3rxWsqgsPi4o7A'
edit_screen_theme: gin
skip_create_form: {  }
mobile_presets:
  -
    name: 'iPhone 12 Pro'
    width: 390
    height: 844
  -
    name: 'iPhone XR'
    width: 414
    height: 896
  -
    name: 'Pixel 5'
    width: 393
    height: 851
dialog_settings:
  _defaults:
    width: fit-content
    height: fit-content
    drupalAutoButtons: false
    dialogClass: lpb-dialog
    resizable: true
bundles:
  node:
    article: article
    experiment: experiment
    feature: feature
    landing: landing
    page: page
    press_release: press_release
    professional_development: professional_development
    report_publication: report_publication
    school_presentation: school_presentation
    standard: standard
