taxonomies:
  audience:
    -
      vid: audience
      tid: '161'
      langcode: en
      name: 'Contractors and vendors'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 72e0b24d-6fd3-4218-b3f7-a797be78c619
    -
      vid: audience
      tid: '156'
      langcode: en
      name: Education
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 48bb2e13-745e-4503-ac0a-e6e7de7962ba
    -
      vid: audience
      tid: '157'
      langcode: en
      name: 'Local community'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: c3f65d73-1ec0-4e70-8d9c-99d214d912a9
    -
      vid: audience
      tid: '159'
      langcode: en
      name: 'Policy maker'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: ff28c6d9-64e5-4aec-bd1f-19120f8b8503
    -
      vid: audience
      tid: '160'
      langcode: en
      name: Press
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 7a53f59d-dada-444d-9df8-0db2366900ec
    -
      vid: audience
      tid: '158'
      langcode: en
      name: 'Researchers and science partners'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 5fb5f8b3-87c7-46ef-ae4c-d9d1cb8cd46e
    -
      vid: audience
      tid: '162'
      langcode: en
      name: 'SURF staff'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: e355bec0-b537-4b15-8109-09a986bb09a2
  eo_opportunity:
    -
      vid: eo_opportunity
      tid: '146'
      langcode: en
      name: 'Classroom activities'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: b29d0e64-b0b1-4d8a-9845-0fa719e93012
    -
      vid: eo_opportunity
      tid: '147'
      langcode: en
      name: 'Field trips'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 76d8c5ad-9cf6-43b8-a991-4b1e02531f61
    -
      vid: eo_opportunity
      tid: '148'
      langcode: en
      name: 'Professional development'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: d57ea925-2c0b-47c0-bb6e-a29fe8aa90f8
    -
      vid: eo_opportunity
      tid: '145'
      langcode: en
      name: 'Public outreach'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 1920b8c7-91b1-4d42-bd13-6ba317594edf
    -
      vid: eo_opportunity
      tid: '149'
      langcode: en
      name: 'Student opportunities'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 65e087de-bb28-48dd-ad9f-d4954920ad66
    -
      vid: eo_opportunity
      tid: '144'
      langcode: en
      name: 'Visitor center'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: bb615311-407c-4dbf-8be0-be4ba057938a
  event_type:
    -
      vid: event_type
      tid: '139'
      langcode: en
      name: Fundraising
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 8b33a53f-2a69-4fab-b140-480559029e30
    -
      vid: event_type
      tid: '140'
      langcode: en
      name: Private
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: e63404c3-d7e0-48c4-a2a3-0daee4d9c899
    -
      vid: event_type
      tid: '138'
      langcode: en
      name: Public
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 90207067-376c-4b72-9421-8fb19574622a
  key_impact_area:
    -
      vid: key_impact_area
      tid: '143'
      langcode: en
      name: 'Beyond the classroom, into the community'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: ca495409-9fdd-4383-91c6-d35ccd5754b0
    -
      vid: key_impact_area
      tid: '141'
      langcode: en
      name: 'Institute for Underground Science'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 1016191d-278d-4153-88ef-fb2a78262c17
    -
      vid: key_impact_area
      tid: '142'
      langcode: en
      name: 'Scientists of the Future'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: ab2d2509-6175-4553-bad1-edd7f7b27641
  reservation_status:
    -
      vid: reservation_status
      tid: '166'
      langcode: en
      name: Delivered
      description__value: null
      description__format: null
      weight: '3'
      parent: '0'
      uuid: 8d48e7f6-f76e-439f-bb35-125d49672d42
    -
      vid: reservation_status
      tid: '165'
      langcode: en
      name: 'In shipment'
      description__value: null
      description__format: null
      weight: '2'
      parent: '0'
      uuid: 985f3f3c-143b-4c0f-9431-129008b7a250
    -
      vid: reservation_status
      tid: '164'
      langcode: en
      name: 'Processing for delivery'
      description__value: null
      description__format: null
      weight: '1'
      parent: '0'
      uuid: 671c7a14-8669-49ec-9dc5-cdc3a630b737
    -
      vid: reservation_status
      tid: '163'
      langcode: en
      name: Requested
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: bbbd7966-4b1b-4a47-a06f-65dbf0db7c95
    -
      vid: reservation_status
      tid: '167'
      langcode: en
      name: Returned
      description__value: null
      description__format: null
      weight: '4'
      parent: '0'
      uuid: e8657a29-3706-416a-87d0-21b98b43b2ca
