<?php

/**
 * @file
 * hearsay_preview module file.
 */

/**
 * Implements hook_theme().
 */
function hearsay_preview_theme()
{
    return [
        'expired_page' => [
            'variables' => [
                'items' => [],
            ],
        ],
    ];
}

/**
 * Alter the data of a sitemap link before the link is saved.
 *
 * @param array $link
 *   An array with the data of the sitemap link.
 * @param array $context
 *   An optional context array containing data related to the link.
 */
function hearsay_preview_xmlsitemap_link_alter(array &$link, array $context)
{
    $alias = \Drupal::service('path_alias.manager')->getAliasByPath($link['loc']);
    if (strpos($alias, "/preview") !== false) {
        // Status is set to zero to exclude the item in the sitemap.
        $link['status'] = 0;
        // Set to zero to make the element non-accessible by the anonymous user.
        $link['access'] = 0;
    }
}
