title: Surf Main/Header
args:
  heading: Header Title
argTypes:
  header_text_style:
    title: Header text style
    description: The link target attribute
    control: select
    options:
      White: white-text
      Black: black-text
  header_particle_style:
    title: Header text style
    description: The link target attribute
    control: select
    options:
      # None: no-particles
      Green: green-particles
      LightGray: light-gray-particles
      White: white-particles

stories:
  - name: White Text
    args:
      # header_particle_style: no-particles
      header_text_style: white-text
  - name: Green Particle White Text
    args:
      header_particle_style: green-particles
      header_text_style: white-text
  - name: Light Gray Particle White Text
    args:
      header_particle_style: light-gray-particles
      header_text_style: white-text
  - name: Black Text
    args:
      # header_particle_style: no-particles-particles
      header_text_style: black-text
  - name: Green Particle Black Text
    args:
      header_particle_style: green-particles
      header_text_style: black-text
  - name: Light Gray Particle Black Text
    args:
      header_particle_style: light-gray-particles
      header_text_style: black-text
  - name: White Particle Black Text
    args:
      header_particle_style: white-particles
      header_text_style: black-text
