title: Surf Main/List
stories:
  - name: Default
    args:
      style: default-column
      items:
        - |
          {{ 'twig stuff' }}
        - |
          {{ 'twig stuff' }}
        - |
          {{ 'twig stuff' }}
